### ISSUE TITLE
edition values

### ISSUE THREAD

**Issue by liu2005678** [sagc-bioinformatics/mgikit#10]
During the install process: "cargo build --release", it reports:

error: failed to parse manifest at `/home/logen/programs/mgikit/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

**Comment by ziadbkh** [comment]
Please update the version of Rust on your machine to the latest available version and try again. Edition 2021 was added with Rust 1.56.0

**Comment by liu2005678** [comment]
Thanks! it works.

**Comment by liu2005678** [comment]
There is another problem. Though I under stand the structure of read2 ( the reverse strain). I did not completely understand what do you mean by the "Sample sheet" and "Barcode template". Do you have an example of "sample_sheet_expected.tsv " file!

**Comment by liu2005678** [comment]
I used  barcode sequence of  suppliers other than BGI. I now  have the barcode sequence. and i can read  by zcat that the barcode seqence located at the tail of read2. now i want to demultiplex!

**Comment by liu2005678** [comment]
do your program support multi-threads?

**Comment by ziadbkh** [comment]
We have implemented a beta version of multi-threading v1.0.0-beta:
https://github.com/sagc-bioinformatics/mgikit/releases
We are releasing the final version soon with better support for multi-threading.

Details on demultiplexing and examples are at:
https://sagc-bioinformatics.github.io/mgikit/demultiplex
