### ISSUE TITLE
Illumina header conversion creates corrupted files

### ISSUE THREAD

**Issue by xsvato01** [sagc-bioinformatics/mgikit#6]
Hi, I am having problems with demultiplexed files that were run without --disable-illumina option. Every now and then there is a wrongly parsed header that creates 5 lines in fastq file per read.

See the '@;H' header name with the actual name being on the next line.

![Screen Shot 2024-02-26 at 09 14 01](https://github.com/sagc-bioinformatics/mgikit/assets/44240739/ce129809-ca84-4cf4-ad98-25ed9e52c8f5)

**Comment by ziadbkh** [comment]
@xsvato01: which version did you use? you can see it in the log. Please share the log if possible.

**Comment by ziadbkh** [comment]
This was an issue with V0.1.3. the version V0.1.4 should resolve it! Please confirm with me.

**Comment by xsvato01** [comment]
Sweet! Everything fine with V0.1.4.

Not sure if this feature got changed in V0.1.4, but I did not like that in V0.1.3 basecalling would not start if most barcodes were not detected. I would welcome this as a warning but not as a hard stop (e.g. when you are doing partial demultiplexing/debugging). 

Otherwise great tool! Finally a tool with proper docs. The official MGISplitBarcode is awful.

**Comment by ziadbkh-s2s** [comment]
you can use `--ignore-undetermined` param now to make it just a warning.

**Comment by ziadbkh** [comment]
@xsvato01 you can use `--ignore-undetermined` to make it just a warning. not heavily tested but should work.
